experiment-name: test
use_gpu: yes

evaluator: ucr_evaluator

logging:
  logger-name: anomaly-detection
  log-location: ./out/runs/test

augmentation:
  name: "vae_generate"
#  name: vae_generate
  config:
    generator_location: "./out/runs/hp_sweep/generator_hp_sweep/generator_hp_sweep-2022-10-30-10-57-21/model-checkpoints/model-final.pkl"
    std: 0.1
    mean: 0.0


autoencoder:
  type: VAE
  latent_dim: 10
  encoder:
    layers:
      - name: LSTM
        config:
          input_size: 25
          hidden_size: 25
          num_layers: 1
          batch_first: true
      - name: RNNExtract
      - name: Reshape
        config:
          out_shape: [ -1, 2500 ]
      - name: ReLU
      - name: Linear
        config:
          in_features: 2500
          out_features: 512
      - name: ReLU
      - name: Linear
        config:
          in_features: 512
          out_features: 128
      - name: ReLU
      - name: Linear
        config:
          in_features: 128
          out_features: 10
  decoder:
    layers:
      - name: Linear
        config:
          in_features: 10
          out_features: 128
      - name: ReLU
      - name: Linear
        config:
          in_features: 128
          out_features: 512
      - name: ReLU
      - name: Linear
        config:
          in_features: 512
          out_features: 2500
      - name: ReLU
      - name: Reshape
        config:
          out_shape: [ -1, 100, 25 ]
      - name: LSTM
        config:
          input_size: 25
          hidden_size: 25
          num_layers: 1
          batch_first: true
      - name: RNNExtract
      - name: ReLU

training:
  trainer_name: 'vae_trainer'
  epochs: 10
  batch_size: 512
  kl_weight: 1.0e-10
  infos: True
  save_checkpoint: true
  checkpoint_interval: 50
  save_best: true
  save_latest: true

data:
  data-set: ctu
  location: /home/robin/Documents/lbnl/crd/ctu-13/CTU-13-Dataset/
  # will be overridden by main function with run_dir
  #  cache_location: ./data-cache/ucr
  #  set_number: '197'
  set_number: 5
  t_steps: 100
  period_len: 5
  cache_name: 'ctu-'
  compression: zip

downstream:
  type: 'DDD'
  config:
    batch_size: 10000
    density:
      type: 'kdepy'
      config:
        plot_density: True
        #        bandwith: 'ISJ'
        bandwith: 'silverman'
