use_gpu: yes

autoencoder:
  type: VAE
  latent_dim: 4
  encoder:
    layers:
      - name: LSTM
        config:
          input_size: 1
          hidden_size: 1
          num_layers: 1
          batch_first: true
      - name: RNNExtract
      - name: Reshape
        config:
          out_shape: [ -1, 175 ]
      - name: ReLU
      - name: Linear
        config:
          in_features: 175
          out_features: 10
  decoder:
    layers:
      - name: Linear
        config:
          in_features: 4
          out_features: 24
      - name: ReLU
      - name: Linear
        config:
          in_features: 24
          out_features: 175
      - name: ReLU
      - name: Reshape
        config:
          out_shape: [ -1, 175,1 ]
      - name: LSTM
        config:
          input_size: 1
          hidden_size: 1
          num_layers: 1
          batch_first: true
      - name: RNNExtract

training:
  trainer_name: 'vae_trainer'
  epochs: 500
  batch_size: 1024
  kl_weight: 1.0e-5
  infos: true

data:
  data-set: ucr
  location: /home/robin/Documents/lbnl/crd/datasets/AnomalyDatasets_2021/UCR_TimeSeriesAnomalyDatasets2021/FilesAreInHere/UCR_Anomaly_FullData
  cache_location: ./data-cache/ucr
  set_number: '139'
  t_steps: 175
  cache_name: 'ucr-002-90'

downstream:
  type: 'SRD'
  config:
    #    batch_size: 512
    density:
      type: 'kdepy'
      config:
        plot_density: True
        bandwith: 'ISJ'

